#
# Makefile (should be replaced by autotools or something else)
#
###################################################################################
#     $Id: Makefile,v 1.1 2007-09-13 08:48:06 cvsyan Exp $
###################################################################################

VERSION=0.1.0

dist:
	tar zcv --exclude-from=exclude-file -f code-$(VERSION).tgz code
	

