// Persistence Of Vision Ray Tracer Scene Description File
// --------------------------------------------------------------------------------
// common.inc


// 
#declare myFast=1;


// This wont change soon
#declare m =       100;
#declare km=    m*1000;
#declare Mm=   km*1000; // 1000 km
#declare Gm=   Mm*1000; // 1000 000 km
#declare cm=    m/100;
#declare mm=    m/1000;
#declare um=   mm/1000;

